postgres:
  image: postgres:9.6.3
  environment:
    - POSTGRES_USER=developer
    - POSTGRES_PASSWORD=development_secret
    - POSTGRES_DB=connector
  ports:
    - 5432:5432

rabbitmq:
  image: rabbitmq:3.7.2-management
  environment:
    - RABBITMQ_DEFAULT_PASS:guest
    - RABBITMQ_DEFAULT_USER:guest
  ports:
    - 5672:5672
    - 15673:15672

postgres_test:
  image: postgres:9.6.3
  environment:
    - POSTGRES_USER=developer
    - POSTGRES_PASSWORD=development_secret
    - POSTGRES_DB=connector_test
  ports:
    - 5433:5432
